In [3]:
%pip install lxml

Requirement already satisfied: lxml in c:\users\sally\sknpyworkspace\streamlit\lib\site-packages (6.0.2)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

# HTML 파일 경로 or 웹 페이지 주소를 url 변수에 저장
url = './data/sample.html'

# HTML 웹페이지의 표(table)를 가져와서 데이터프레임으로 변환 
tables = pd.read_html(url)   

# 표(table)의 개수 확인
print(len(tables))

2

In [10]:
len(tables)

2

In [ ]:
# 첫 번째 표(table)를 데이터프레임으로 변환
tables[0]

   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9

In [5]:
# tables 리스트의 원소를 iteration하면서 각각 화면 출력
for i in range(len(tables)):
    print(f"tables[{i}]")
    print(tables[i])
    print('\n')

tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9


tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [6]:
# 파이썬 패키지 정보가 들어 있는 두 번째 데이터프레임을 선택하여 df 변수에 저장
df = tables[1] 
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [7]:
# 'name' 열을 인덱스로 지정
df = df.set_index(['name'])
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True