In [3]:
# 고객 이탈에 여부 분류 모델
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
# 데이터 읽기
import pandas as pd
df = pd.read_csv(url)
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

#### 1. 데이터 기본 정보 확인

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.select_dtypes(include=['object'])

      customerID  gender Partner  ...              PaymentMethod TotalCharges Churn
0     7590-VHVEG  Female     Yes  ...           Electronic check        29.85    No
1     5575-GNVDE    Male      No  ...               Mailed check       1889.5    No
2     3668-QPYBK    Male      No  ...               Mailed check       108.15   Yes
3     7795-CFOCW    Male      No  ...  Bank transfer (automatic)      1840.75    No
4     9237-HQITU  Female      No  ...           Electronic check       151.65   Yes
...          ...     ...     ...  ...                        ...          ...   ...
7038  6840-RESVB    Male     Yes  ...               Mailed check       1990.5    No
7039  2234-XADUH  Female     Yes  ...    Credit card (automatic)       7362.9    No
7040  4801-JZAZL  Female     Yes  ...           Electronic check       346.45    No
7041  8361-LTMKD    Male     Yes  ...               Mailed check        306.6   Yes
7042  3186-AJIEK    Male      No  ...  Bank transfer (automatic)       6844.5    No

[7043 rows x 18 columns]

In [6]:
df['TotalCharges'] = pd.to_numeric(df.TotalCharges,errors='coerce')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [8]:
# Churn Yes No --> 1 0 으로 변경
df['Churn'] =  df.Churn.map({'Yes':1,'No':0})
# df.Churn.apply(lambda x : 1 if x=='Yes' else 0)

#### baseline 데이터 및 모델 생성

In [9]:
# 피처선택 
base_df =  df.select_dtypes(include=['int','float']).copy()
# 결측치 처리
base_df = base_df.dropna()
X = base_df.drop(columns=['Churn']).to_numpy()
y = base_df.Churn
# 클래스 불균형


# 데이터 분할
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,stratify=y,test_size=0.2,random_state=42)
# 스케일링
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled =  scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
# 모델
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
# 학습
knn.fit(x_train_scaled, y_train)
# 평가
from sklearn.metrics import classification_report
predict = knn.predict(x_test_scaled)
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.82      0.88      0.84      1033
           1       0.57      0.45      0.51       374

    accuracy                           0.76      1407
   macro avg       0.69      0.66      0.67      1407
weighted avg       0.75      0.76      0.75      1407